[project]
name = "gente"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "bcrypt>=5.0.0",
    "pyjwt>=2.13.0",
    "fastapi[standard]>=0.128.8",
    "google-genai>=1.47.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.3",
    "yt-dlp>=2025.1.26",
    "boto3>=1.42.97",
    "botocore[crt]>=1.42.97",
]
